title: svtplay-dl
email: j@i19.se
description: >- # this means to ignore newlines until "baseurl:"
  Small command-line program to download videos from various sites.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://svtplay-dl.se" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: j0hanandersson
github_username:  spaam
google_analytics: UA-67802142-1

# Build settings
# Below remote theme is usable, but for this site it's included in source instead.
# remote_theme: granbom/jekyll-theme-bootstrap4-navbar-cdn

permalink: /:title/
navbar: light # other option dark
navbar-bg: light # other option dark
navbar-fixed-top: false  # if true, also add _sass/bootstrap4-cdn.scss padding top

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "spaam"
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      author: "spaam"
      layout: "page"

# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
   - README.md
   - LICENSE
